apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      name: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '1234'
        ports:
        - containerPort: 3305
