apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/tae/class17/lab2/pv0001/
  storageClassName: ""
  claimRef:
    namespace: default
    name: nginx-pvc
